
package pe.com.hiveit.eai.ws.factsys.loginws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import pe.com.hiveit.eai.ws.factsys.loginws.types.ConsultUserRequest;
import pe.com.hiveit.eai.ws.factsys.loginws.types.ConsultUserResponse;
import pe.com.hiveit.eai.ws.factsys.loginws.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LoginWSPortType", targetNamespace = "http://hiveit.com.pe/eai/ws/factsys/loginws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginWSPortType {


    /**
     * 
     * @param request
     * @return
     *     returns pe.com.hiveit.eai.ws.factsys.loginws.types.ConsultUserResponse
     */
    @WebMethod(action = "http://hiveit.com.pe/eai/ws/factsys/loginws/consultUser")
    @WebResult(name = "consultUserResponse", targetNamespace = "http://hiveit.com.pe/eai/ws/factsys/loginws/types", partName = "response")
    public ConsultUserResponse consultUser(
        @WebParam(name = "consultUserRequest", targetNamespace = "http://hiveit.com.pe/eai/ws/factsys/loginws/types", partName = "request")
        ConsultUserRequest request);

}
