package pe.com.hiveit.eai.ws.factsys.loginws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.soap.SOAPBinding;

import pe.com.hiveit.eai.ws.factsys.loginws.service.LoginServiceImpl;
import pe.com.hiveit.eai.ws.factsys.loginws.types.ConsultUserRequest;
import pe.com.hiveit.eai.ws.factsys.loginws.types.ConsultUserResponse;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6hudson-86 Generated
 * source version: 2.2
 * 
 */
@WebService(
		portName = "ebsLoginSB11", 
		serviceName = "LoginWSService", 
		targetNamespace = "http://hiveit.com.pe/eai/ws/factsys/loginws", 
		wsdlLocation = "/wsdl/LoginWS.wsdl", 
		endpointInterface = "pe.com.hiveit.eai.ws.factsys.loginws.LoginWSPortType")
@BindingType(SOAPBinding.SOAP11HTTP_BINDING)
public class LoginWSSB11 implements LoginWSPortType {

	LoginServiceImpl  loginServiceImpl = new LoginServiceImpl();
	
	@Override
	@WebMethod(action = "http://hiveit.com.pe/eai/ws/factsys/loginws/consultUser")
    @WebResult(name = "consultUserResponse", targetNamespace = "http://hiveit.com.pe/eai/ws/factsys/loginws/types", partName = "response")
    public ConsultUserResponse consultUser(
        @WebParam(name = "consultUserRequest", targetNamespace = "http://hiveit.com.pe/eai/ws/factsys/loginws/types", partName = "request")
        ConsultUserRequest request){
		return loginServiceImpl.consultUser(request);
	}	
	 
}
