<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AdminProductWS"
	targetNamespace="http://cmc.com.pe/eai/ws/facsys/adminproductws"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:tns="http://cmc.com.pe/eai/ws/facsys/adminproductws"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
	xmlns:types="http://cmc.com.pe/eai/ws/facsys/adminproductws/types">

	<types>
		<xsd:schema targetNamespace="http://cmc.com.pe/eai/ws/facsys/adminproductws"
			elementFormDefault="qualified" />
		<xsd:schema>
			<xsd:import schemaLocation="AdminProductWS.xsd"
				namespace="http://cmc.com.pe/eai/ws/facsys/adminproductws/types" />
		</xsd:schema>
	</types>

	<wsdl:message name="changeRequestMsg">
		<wsdl:part name="request" element="types:changeRequest" />
	</wsdl:message>

	<wsdl:message name="changeResponseMsg">
		<wsdl:part name="response" element="types:changeResponse" />
	</wsdl:message>

	<wsdl:portType name="AdminProductWSPortType">
		<wsdl:operation name="change">
			<wsdl:input message="tns:changeRequestMsg" />
			<wsdl:output message="tns:changeResponseMsg" />
		</wsdl:operation>
	</wsdl:portType>

	<!-- SOAP version 1.1 -->
	<wsdl:binding name="AdminProductWSPortTypeSOAP11Binding"
		type="tns:AdminProductWSPortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="change">
			<soap:operation style="document"
				soapAction="http://cmc.com.pe/eai/ws/facsys/adminproductws/change" />
			<wsdl:input>
				<soap:body use="literal" parts="request" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="response" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<!-- SOAP version 1.2 -->
	<wsdl:binding name="AdminProductWSPortTypeSOAP12Binding"
		type="tns:AdminProductWSPortType">
		<soap12:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="change">
			<soap12:operation style="document"
				soapAction="http://cmc.com.pe/eai/ws/facsys/adminproductws/change" />
			<wsdl:input>
				<soap12:body use="literal" parts="request" />
			</wsdl:input>
			<wsdl:output>
				<soap12:body use="literal" parts="response" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<!-- Servicio SOAP versiones 11, 12 -->
	<wsdl:service name="AdminProductWSService">
		<wsdl:port name="ebsAdminProductSB11" binding="tns:AdminProductWSPortTypeSOAP11Binding">
			<soap:address location="http://127.0.0.1:9990/AdminProductWS/ebsAdminProductSB11" />
		</wsdl:port>

		<wsdl:port name="ebsAdminProductSB12" binding="tns:AdminProductWSPortTypeSOAP12Binding">
			<soap12:address location="http://127.0.0.1:9990/AdminProductWS/ebsAdminProductSB12" />
		</wsdl:port>
	</wsdl:service>
</definitions>
