<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="LoginWS" 
	targetNamespace="http://hiveit.com.pe/eai/ws/sisfact/loginws"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:tns="http://hiveit.com.pe/eai/ws/sisfact/loginws"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
	xmlns:types="http://hiveit.com.pe/eai/ws/sisfact/loginws/types">

	<types>
		<xsd:schema targetNamespace="http://hiveit.com.pe/eai/ws/sisfact/loginws"
			elementFormDefault="qualified" />
		<xsd:schema>
			<xsd:import schemaLocation="LoginWS.xsd"
				namespace="http://hiveit.com.pe/eai/ws/sisfact/loginws/types" />
		</xsd:schema>
	</types>
	
	<wsdl:message name="consultarUserRequestMsg">
  		<wsdl:part name="request" element="types:consultarUserRequest"/>
  	</wsdl:message>

  	<wsdl:message name="consultarUserResponseMsg">
  		<wsdl:part name="response"  element="types:consultarUserResponse"/>
  	</wsdl:message> 	 	
  	
  	<wsdl:portType name="LoginType">
  
    <wsdl:operation name="consultarUser">
      <wsdl:input message="tns:consultarUserRequestMsg" />
      <wsdl:output message="tns:consultarUserResponseMsg" />
    </wsdl:operation>
    
  </wsdl:portType>
	
	<!-- SOAP version 1.1 -->
	<wsdl:binding name="LoginTypeSOAP11Binding"
		type="tns:LoginType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="consultarUser">
			<soap:operation style="document"
				soapAction="http://hiveit.com.pe/eai/ws/sisfact/loginws/consultarUser" />
			<wsdl:input>
				<soap:body use="literal" parts="request" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="response" />
			</wsdl:output>
		</wsdl:operation>
				
	</wsdl:binding>	
	
	 <!-- SOAP version 1.2 -->
	<wsdl:binding name="LoginTypeSOAP12Binding"
		type="tns:LoginType">
		<soap12:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="consultarUser">
			<soap12:operation style="document"
				soapAction="http://hiveit.com.pe/eai/ws/sisfact/loginws/consultarUser" />
			<wsdl:input>
				<soap12:body use="literal" parts="request" />
			</wsdl:input>
			<wsdl:output>
				<soap12:body use="literal" parts="response" />
			</wsdl:output>
		</wsdl:operation>
		
	</wsdl:binding>
	
	<!-- Servicio SOAP versiones 11, 12 -->
	<wsdl:service name="LoginWSService">
		<wsdl:port name="ebsLoginSB11" binding="tns:LoginTypeSOAP11Binding">
			<soap:address location="http://127.0.0.1:7001/Loginws/ebsLoginSB11" />
		</wsdl:port>
		<wsdl:port name="ebsLoginSB12" binding="tns:LoginTypeSOAP12Binding">
			<soap12:address location="http://127.0.0.1:7001/Loginws/ebsLoginSB12" />
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>