package pe.com.hiveit.eai.ws.factsys.adminproductws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(
		name = "AdminProductWSService", 
		targetNamespace = "http://hiveit.com.pe/eai/ws/factsys/adminproductws", 
		wsdlLocation = "/WEB-INF/wsdl/AdminProductWS.wsdl")

public class AdminProductWSService
    extends Service
 {
	private final static URL ADMINPRODUCTWSSERVICE_WSDL_LOCATION;
	private final static WebServiceException ADMINPRODUCTWSSERVICE_EXCEPTION;
	private final static QName ADMINPRODUCTWSSERVICE_QNAME = new QName(
			"/WEB-INF/wsdl/AdminProductWS.wsdl", "AdminProductWSService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = pe.com.hiveit.eai.ws.factsys.adminproductws.AdminProductWSService.class
					.getResource("/WEB-INF/wsdl/AdminProductWS.wsdl");
			if (url == null) {
				throw new MalformedURLException(
						"/WEB-INF/wsdl/AdministrarCodigosSecretosWS.wsdl does not exist in the module");
			}
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		ADMINPRODUCTWSSERVICE_WSDL_LOCATION = url;
		ADMINPRODUCTWSSERVICE_EXCEPTION = e;
	}

	public AdminProductWSService() {
		super(__getWsdlLocation(), ADMINPRODUCTWSSERVICE_QNAME);
	}

	public AdminProductWSService(WebServiceFeature... features) {
		super(__getWsdlLocation(), ADMINPRODUCTWSSERVICE_QNAME, features);
	}

	public AdminProductWSService(URL wsdlLocation) {
		super(wsdlLocation, ADMINPRODUCTWSSERVICE_QNAME);
	}

	public AdminProductWSService(URL wsdlLocation,
			WebServiceFeature... features) {
		super(wsdlLocation, ADMINPRODUCTWSSERVICE_QNAME, features);
	}

	public AdminProductWSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public AdminProductWSService(URL wsdlLocation, QName serviceName,
			WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns AdminProductWSPortType
	 */
	@WebEndpoint(name = "ebsAdminProductSB11")
	public AdminProductWSPortType getEbsAdminProductSB11() {
		return super
				.getPort(
						new QName(
								"http://hiveit.com.pe/eai/ws/factsys/adminproductws",
								"ebsAdminProductSB11"),
						AdminProductWSPortType.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns AdministrarCodigosSecretosWSPortType
	 */
	@WebEndpoint(name = "ebsAdminProductSB11")
	public AdminProductWSPortType getEbsAdminProductSB11(
			WebServiceFeature... features) {
		return super
				.getPort(
						new QName(
								"http://hiveit.com.pe/eai/ws/factsys/adminproductws",
								"ebsAdminProductSB11"),
						AdminProductWSPortType.class, features);
	}

	private static URL __getWsdlLocation() {
		if (ADMINPRODUCTWSSERVICE_EXCEPTION != null) {
			throw ADMINPRODUCTWSSERVICE_EXCEPTION;
		}
		return ADMINPRODUCTWSSERVICE_WSDL_LOCATION;
	}

}
