
package pe.com.hiveit.eai.ws.factsys.adminuserws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LoginWSService", targetNamespace = "http://hiveit.com.pe/eai/ws/sisfact/loginws", wsdlLocation = "file:/C:/Users/jcisnera/Desktop/HiveIT/Development/generar/LoginWS.wsdl")
public class AdminUserWSService
    extends Service
{

    private final static URL LOGINWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(pe.com.hiveit.eai.ws.factsys.adminuserws.AdminUserWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = pe.com.hiveit.eai.ws.factsys.adminuserws.AdminUserWSService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/jcisnera/Desktop/HiveIT/Development/generar/LoginWS.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/jcisnera/Desktop/HiveIT/Development/generar/LoginWS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOGINWSSERVICE_WSDL_LOCATION = url;
    }

    public AdminUserWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminUserWSService() {
        super(LOGINWSSERVICE_WSDL_LOCATION, new QName("http://hiveit.com.pe/eai/ws/sisfact/loginws", "LoginWSService"));
    }

    /**
     * 
     * @return
     *     returns LoginType
     */
    @WebEndpoint(name = "ebsLoginSB11")
    public AdminUserWSPortType getEbsLoginSB11() {
        return super.getPort(new QName("http://hiveit.com.pe/eai/ws/sisfact/loginws", "ebsLoginSB11"), AdminUserWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginType
     */
    @WebEndpoint(name = "ebsLoginSB11")
    public AdminUserWSPortType getEbsLoginSB11(WebServiceFeature... features) {
        return super.getPort(new QName("http://hiveit.com.pe/eai/ws/sisfact/loginws", "ebsLoginSB11"), AdminUserWSPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns LoginType
     */
    @WebEndpoint(name = "ebsLoginSB12")
    public AdminUserWSPortType getEbsLoginSB12() {
        return super.getPort(new QName("http://hiveit.com.pe/eai/ws/sisfact/loginws", "ebsLoginSB12"), AdminUserWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginType
     */
    @WebEndpoint(name = "ebsLoginSB12")
    public AdminUserWSPortType getEbsLoginSB12(WebServiceFeature... features) {
        return super.getPort(new QName("http://hiveit.com.pe/eai/ws/sisfact/loginws", "ebsLoginSB12"), AdminUserWSPortType.class, features);
    }

}
