
package pe.com.cmc.eai.ws.facsys.adminproductws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import pe.com.cmc.eai.ws.facsys.adminproductws.types.ChangeRequest;
import pe.com.cmc.eai.ws.facsys.adminproductws.types.ChangeResponse;
import pe.com.cmc.eai.ws.facsys.adminproductws.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdminProductWSPortType", targetNamespace = "http://cmc.com.pe/eai/ws/facsys/adminproductws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdminProductWSPortType {


    /**
     * 
     * @param request
     * @return
     *     returns pe.com.cmc.eai.ws.facsys.adminproductws.types.ChangeResponse
     */
    @WebMethod(action = "http://cmc.com.pe/eai/ws/facsys/adminproductws/change")
    @WebResult(name = "changeResponse", targetNamespace = "http://cmc.com.pe/eai/ws/facsys/adminproductws/types", partName = "response")
    public ChangeResponse change(
        @WebParam(name = "changeRequest", targetNamespace = "http://cmc.com.pe/eai/ws/facsys/adminproductws/types", partName = "request")
        ChangeRequest request);

}
