package pe.com.cmc.eai.ws.facsys.adminproductws;

import javax.annotation.PostConstruct;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.soap.SOAPBinding;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.context.support.SpringBeanAutowiringSupport;

import pe.com.cmc.eai.ws.facsys.adminproductws.service.AdminProductService;
import pe.com.cmc.eai.ws.facsys.adminproductws.types.ChangeRequest;
import pe.com.cmc.eai.ws.facsys.adminproductws.types.ChangeResponse;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6hudson-86 Generated
 * source version: 2.2
 * 
 */
@WebService(
		portName = "ebsAdminProductSB12", 
		serviceName = "AdminProductWSService", 
		targetNamespace = "http://cmc.com.pe/eai/ws/facsys/adminproductws", 
		wsdlLocation = "/WEB-INF/wsdl/AdminProductWS.wsdl", 
		endpointInterface = "pe.com.cmc.eai.ws.facsys.adminproductws.AdminProductWSPortType")
@BindingType(SOAPBinding.SOAP11HTTP_BINDING)
public class AdminProductWSSB12 implements AdminProductWSPortType {

	@Autowired
	AdminProductService adminProductService;
	
	@PostConstruct
	public void init() {
		SpringBeanAutowiringSupport.processInjectionBasedOnCurrentContext(this);
	}
	 /**
     * 
     * @param request
     * @return
     *     returns pe.com.claro.eai.ws.portalclaro.administrarcodigossecretosws.types.EnviarCodigoSecretolResponse
     */
	@Override
    @WebMethod(action = "http://cmc.com.pe/eai/ws/facsys/adminproductws/change")
    @WebResult(name = "changeResponse", 
    targetNamespace = "http://cmc.com.pe/eai/ws/facsys/adminproductws/types", 
    partName = "response")
    public ChangeResponse change(
        @WebParam(name = "changeRequest", 
        targetNamespace = "http://cmc.com.pe/eai/ws/facsys/adminproductws/types", partName = "request")
        ChangeRequest request){
		return adminProductService.change(request);
	}	
}
